# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.4
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: 33459750+papismurf@users.noreply.github.com
author_name: dbpython
preset_name: starter
project_name: bankichain-frontend

